sudo: required

language: python

dist: xenial

os:
  - linux

python:
  #  - "3.5" Disabled because ROS can't run with Python 3.
  - "2.7"

before_script:
  - ./install.sh

script:
  - ./tests/run_tests.sh
